### ISSUE TITLE
Regression on payload validations on POST `/v2/evc/`

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#117]
Today when we've fixed the docker build, I've retried to re-run the tests, noticed some failures (we'll get the rest of the list on tonight's execution), but this one here for instance, fails with an unexpected client side 400 error:

```
collected 189 items / 188 deselected
tests/test_e2e_10_mef_eline.py F                                         [100%]
=================================== FAILURES ===================================
____ TestE2EMefEline.test_050_on_primary_path_fail_should_migrate_to_backup ____
self = <tests.test_e2e_10_mef_eline.TestE2EMefEline instance at 0x7f0095632a28>
    def test_050_on_primary_path_fail_should_migrate_to_backup(self)
```

```
{
    "code": 400,
    "description": "Additional properties are not allowed ('backup_path' was unexpected) for field .",
    "name": "Bad Request"
}
```

You can reproduce the issue with this payload for example:

```
{
    "name": "my evc1",
    "enabled": true,
    "uni_a": {
        "interface_id": "00:00:00:00:00:00:00:01:1"
    },
    "uni_z": {
        "interface_id": "00:00:00:00:00:00:00:03:1"
    },
    "primary_path": [
        {
            "endpoint_a": {
                "id": "00:00:00:00:00:00:00:01:2"
            },
            "endpoint_b": {
                "id": "00:00:00:00:00:00:00:02:2"
            }
        },
        {
            "endpoint_a": {
                "id": "00:00:00:00:00:00:00:02:3"
            },
            "endpoint_b": {
                "id": "00:00:00:00:00:00:00:03:2"
            }
        }
    ],
    "backup_path": [
        {
            "endpoint_a": {
                "id": "00:00:00:00:00:00:00:01:3"
            },
            "endpoint_b": {
                "id": "00:00:00:00:00:00:00:03:3"
            }
        }
    ]
}
```

It looks like it's something related to the current [`openapi.yml` spec and the `NewCircuit` schema with the `backup_path` key](https://github.com/kytos-ng/mef_eline/blob/master/openapi.yml#L315-L319)

**Comment by viniarck** [comment]
Another traceback that also showed up with this payload: 

```
{
    "name": "my evc1",
    "enabled": "true",
    "uni_a": {
        "interface_id": "00:00:00:00:00:00:00:01:1",
        "tag": {
            "tag_type": 1,
            "value": 101
        }
    },
    "uni_z": {
        "interface_id": "00:00:00:00:00:00:00:03:1",
        "tag": {
            "tag_type": 1,
            "value": 101
        }
    },
    "primary_path": [
        {
            "endpoint_a": {
                "id": "00:00:00:00:00:00:00:01:3"
            },
            "endpoint_b": {
                "id": "00:00:00:00:00:00:00:02:2"
            }
        },
        {
            "endpoint_a": {
                "id": "00:00:00:00:00:00:00:02:3"
            },
            "endpoint_b": {
                "id": "00:00:00:00:00:00:00:03:2"
            }
        }
    ]
}
```

```
kytos $> 2022-01-07 10:59:56,596 - INFO [kytos.napps.kytos/topology] (ThreadPoolExecutor-0_0) There is no status saved to restore.
2022-01-07 10:59:56,596 - INFO [kytos.napps.kytos/topology] (ThreadPoolExecutor-0_6) There is no status saved to restore.
2022-01-07 10:59:58,375 - INFO [kytos.napps.kytos/mef_eline] (Thread-15) error response: {'error_message': "'endpoints' is a required property", 'error_validator': 'required', 'error_val
idator_value': ['endpoints'], 'error_path': ['primary_path', 0], 'error_schema': {'type': 'object', 'required': ['endpoints'], 'properties': {'id': {'type': 'integer', 'format': 'int32'}
, 'endpoints': {'type': 'array', 'items': {'$ref': '#/components/schemas/Endpoint', 'x-scope': ['', '#/components/schemas/Circuit', '#/components/schemas/Path']}}}, 'nullable': False}, '
error_schema_path': ['properties', 'primary_path', 'items', 'required']}
2022-01-07 10:59:58,376 - ERROR [kytos.core.controller] (Thread-15) Exception on /api/kytos/mef_eline/v2/evc/ [POST]
Traceback (most recent call last):
  File "/home/viniarck/repos/kytos/.direnv/python-3.6.15/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/viniarck/repos/kytos/.direnv/python-3.6.15/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/viniarck/repos/kytos/.direnv/python-3.6.15/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/viniarck/repos/kytos/.direnv/python-3.6.15/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/viniarck/repos/kytos/.direnv/python-3.6.15/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/viniarck/repos/kytos/.direnv/python-3.6.15/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/viniarck/repos/kytos/.direnv/python-3.6.15/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/viniarck/repos/napps/../napps/kytos/mef_eline/utils.py", line 82, in wrapper_validate
    error_response += f" {'/'.join(schema_errors.path)}."
TypeError: sequence item 1: expected str instance, int found
```

We'd also probably have to make sure it's safe to use this join, since as showed in this example, an integer was also included in that list, so might need to map it first https://github.com/kytos-ng/mef_eline/blob/master/utils.py#L82
