### ISSUE TITLE
Premature deploy of the EVCs

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/mef_eline#218]
Hi,

There is a possible corner case when the controller has just started and link_up events may end up making the EVCs to be (re)deployed. See the log messages below to a possible example of such scenario

```
Nov 10 15:17:01 kytos-dev kytos.core.db:INFO db:134:  Starting DB connection
Nov 10 15:17:01 kytos-dev kytos.core.db:INFO db:119:  Trying to run 'hello' command on MongoDB...
Nov 10 15:17:01 kytos-dev kytos.core.db:INFO db:121:  Ran 'hello' command on MongoDB successfully. It's ready!
Nov 10 15:17:01 kytos-dev kytos.core.api_server:INFO api_server:414:  Started /api/kytos/core/auth/login/ - GET
Nov 10 15:17:01 kytos-dev kytos.core.api_server:INFO api_server:414:  Started /api/kytos/core/auth/users/ - GET
Nov 10 15:17:01 kytos-dev kytos.core.api_server:INFO api_server:414:  Started /api/kytos/core/auth/users/<username> - GET
Nov 10 15:17:01 kytos-dev kytos.core.api_server:INFO api_server:414:  Started /api/kytos/core/auth/users/ - POST
Nov 10 15:17:01 kytos-dev kytos.core.api_server:INFO api_server:414:  Started /api/kytos/core/auth/users/<username> - DELETE
Nov 10 15:17:01 kytos-dev kytos.core.api_server:INFO api_server:414:  Started /api/kytos/core/auth/users/<username> - PATCH
Nov 10 15:17:01 kytos-dev kytos.core.controller:INFO controller:265:  //var/run/kytos
Nov 10 15:17:01 kytos-dev kytos.core.controller:INFO controller:315:  Starting Kytos - Kytos Controller
...
Nov 10 15:17:09 kytos-dev kytos.core.api_server:INFO api_server:414:  Started /api/kytos/mef_eline/v2/evc/schedule/<schedule_id> - PATCH
Nov 10 15:17:09 kytos-dev kytos.core.controller:INFO controller:583:  Event handler conn started
Nov 10 15:17:09 kytos-dev kytos.core.controller:INFO controller:583:  Event handler raw started
Nov 10 15:17:09 kytos-dev kytos.core.controller:INFO controller:583:  Event handler msg_in started
Nov 10 15:17:09 kytos-dev werkzeug:WARNING _internal:225:  WebSocket transport not available. Install simple-websocket for improved performance.
Nov 10 15:17:09 kytos-dev kytos.core.controller:INFO controller:610:  Event handler msg_out started
Nov 10 15:17:09 kytos-dev kytos.core.controller:INFO controller:583:  Event handler app started
Nov 10 15:17:09 kytos-dev werkzeug:WARNING _internal:225:   * Running on all addresses.#012   WARNING: This is a development server. Do not use it in a production deployment.
Nov 10 15:17:09 kytos-dev kytos.core.atcp_server:INFO atcp_server:131:  New connection from xxxx:58428
Nov 10 15:17:09 kytos-dev kytos.napps.kytos/of_core:INFO main:138:  Connection ('xxx', 58428), Switch 00:00:00:00:00:00:00:01: OPENFLOW HANDSHAKE COMPLETE
Nov 10 15:17:10 kytos-dev kytos.napps.kytos/flow_manager:INFO main:585:  Send FlowMod from request dpid: 00:00:00:00:00:00:00:01, command: add, force: False, flows_dict: {'flows': [{'priority': 1000, 'table_id': 0, 'cookie': 12321848580485677057, 'match': {'dl_type': 35020, 'dl_vlan': 3799}, 'actions': [{'action_type': 'output', 'port': 4294967293}]}]}
Nov 10 15:17:10 kytos-dev kytos.napps.kytos/flow_manager:INFO main:585:  Send FlowMod from request dpid: 00:00:00:00:00:00:00:01, command: add, force: True, flows_dict: {'flows': [{'table_id': 0, 'match': {'dl_src': 'ee:ee:ee:ee:ee:02'}, 'priority': 50000, 'actions': [{'action_type': 'output', 'port': 4294967293}]}], 'force': True}
Nov 10 15:17:10 kytos-dev kytos.core.atcp_server:INFO atcp_server:131:  New connection from xxx:57772
Nov 10 15:17:10 kytos-dev kytos.core.atcp_server:INFO atcp_server:131:  New connection from xxx:58578
Nov 10 15:17:10 kytos-dev kytos.core.atcp_server:INFO atcp_server:131:  New connection from xxx:38712
Nov 10 15:17:10 kytos-dev kytos.napps.kytos/flow_manager:INFO main:585:  Send FlowMod from request dpid: 00:00:00:00:00:00:00:02, command: delete, force: True, flows_dict: {'flows': [{'cookie': 12268238215241246539, 'cookie_mask': 18446744073709551615}], 'force': True}
Nov 10 15:17:10 kytos-dev kytos.core.controller:ERROR app:1449:  Exception on /api/kytos/flow_manager/v2/delete/00:00:00:00:00:00:00:02 [POST]#012Traceback (most recent call last):#012  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2073, in wsgi_app#012    response = self.full_dispatch_request()#012  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1519, in full_dispatch_request#012    rv = self.handle_user_exception(e)#012  File "/usr/local/lib/python3.9/dist-packages/flask_cors/extension.py", line 165, in wrapped_function#012    return cors_after_request(app.make_response(f(*args, **kwargs)))#012  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1517, in full_dispatch_request#012    rv = self.dispatch_request()#012  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1503, in dispatch_request#012    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)#012  File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 554, in delete#012    return self._send_flow_mods_from_request(dpid, "delete")#012  File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 606, in _send_flow_mods_from_request#012    self._install_flows(command, flows_dict, [switch], reraise_conn=not force)#012  File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 648, in _install_flows#012    self.delete_matched_flows(#012  File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 448, in delete_matched_flows#012    switches[dpid].connection.protocol.version,#012AttributeError: 'NoneType' object has no attribute 'protocol'
Nov 10 15:17:10 kytos-dev kytos.napps.kytos/of_core:INFO main:138:  Connection ('xxx', 57772), Switch 00:00:00:00:00:00:00:02: OPENFLOW HANDSHAKE COMPLETE
Nov 10 15:17:10 kytos-dev kytos.napps.kytos/mef_eline:ERROR evc:542:  Error removing flows from switch 00:00:00:00:00:00:00:02 forEVC EVC(4189a82753a74b, teste 2): {"code":500,"description":"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.","name":"Internal Server Error"}
Nov 10 15:17:10 kytos-dev kytos.napps.kytos/of_core:INFO main:138:  Connection ('xxx', 58578), Switch 00:00:00:00:00:00:00:04: OPENFLOW HANDSHAKE COMPLETE
Nov 10 15:17:10 kytos-dev kytos.napps.kytos/of_core:INFO main:138:  Connection ('xxx', 38712), Switch 00:00:00:00:00:00:00:03: OPENFLOW HANDSHAKE COMPLETE
```

From the logs we cannot be 100% sure about the hypotheses but it is very likely to be that case. 

This is somehow related to https://github.com/kytos-ng/topology/issues/101 but mef_eline should be robust enough to avoid this premature (re)deploy of the EVC (which, by the way, may impose traffic disruption to the user)

**Comment by italovalcy** [comment]
We could leverage the same timer methodology currently being used on the consistency check routine [1] here.

[1] https://github.com/kytos-ng/mef_eline/blob/master/main.py#L110

**Comment by Ktmi** [comment]
Discussed this with @italovalcy. To help with this issue and #365, we plan to have `mef_eline` persist the active state across restarts, and rerun the consistency check from time to time. Persisting the active state should prevent redeploys from activating at startup.
