### ISSUE TITLE
get_metadata("s_vlan").value, AttributeError: 'NoneType' object has no attribute 'value'

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#277]
It turns out that this error `get_metadata("s_vlan").value, AttributeError: 'NoneType' object has no attribute 'value'` showed up again when @italovalcy was conducting exploratory tests experiments. 

Historically, @ajoaoff fixed a same error on PR #220, and for the original issue it solved, but looks like there's more to it. Italo was updating EVC UNIs (200 EVCs, interval 1s) while link down events eventually happens, so that catalyzed the issue, it's scenario high more scalability so eventually the issue surfaced. 

@italovalcy if you have more details or any other script or general information about the issue feel free to add here just so someone else can continue trying to reproduce and fix it. It seems that the impact were related to the failover flows when provisioning uni flow:

```
Feb  3 18:58:12 130c32ca043b kytos.core.helpers:ERROR helpers:151:  listen_to handler: <function Main.on_link_down at 0x7fccac266e50>, args: (<Main(mef_eline, started 140517028943616)>, KytosEvent('kytos/topology.link_down', {'link': Link(Interface('novi_port_11', 11, Switch('00:00:00:00:00:00:00:01')), Interface('novi_port_11', 11, Switch('00:00:00:00:00:00:00:06'))), 'reason': 'link down'}, 0)) traceback: Traceback (most recent call last):,   File "/usr/local/lib/python3.9/dist-packages/kytos/core/helpers.py", line 146, in handler_context_apm,     result = handler(*args),   File "//var/lib/kytos/napps/kytos/mef_eline/main.py", line 657, in on_link_down,     self.handle_link_down(event),   File "//var/lib/kytos/napps/kytos/mef_eline/main.py", line 677, in handle_link_down,     for dpid, flows in evc.get_failover_flows().items():,   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 805, in get_failover_flows,     return self._prepare_uni_flows(self.failover_path, skip_out=True),   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 903, in _prepare_uni_flows,     out_vlan_a = path[0].get_metadata("s_vlan").value, AttributeError: 'NoneType' object has no attribute 'value',
```

It might be a concurrency or race condition issue that's leaving link without a metadata `s_vlan`

**Comment by viniarck** [comment]
This issue showed up on April 11 nightly e2e execution again 

```
Apr 11 14:59:06 runner-rmtk68xb-project-107-concurrent-0 2023-04-11 14:59:06,812 (thread_pool_app_2) kytos.core.helpers:ERROR helpers:140:  listen_to handler: <function Main.on_link_down at 0x7fd08977c940>, args: (<Main(mef_eline, started 140533626869504)>, KytosEvent('kytos/topology.link_down', {'link': Link(Interface('s1-eth4', 4, Switch('00:00:00:00:00:00:00:01')), Interface('s3-eth3', 3, Switch('00:00:00:00:00:00:00:03'))), 'reason': 'link down'}, 0)) traceback: Traceback (most recent call last):,   File "/usr/local/lib/python3.9/dist-packages/kytos/core/helpers.py", line 136, in handler_context,     result = handler(*args),   File "//var/lib/kytos/napps/kytos/mef_eline/main.py", line 710, in on_link_down,     self.handle_link_down(event),   File "//var/lib/kytos/napps/kytos/mef_eline/main.py", line 730, in handle_link_down,     for dpid, flows in evc.get_failover_flows().items():,   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 815, in get_failover_flows,     return self._prepare_uni_flows(self.failover_path, skip_out=True),   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 933, in _prepare_uni_flows,     out_vlan_a = path[0].get_metadata("s_vlan").value, AttributeError: 'NoneType' object has no attribute 'value', 
```

**Comment by viniarck** [comment]
Landed on https://github.com/kytos-ng/mef_eline/pull/375
