### ISSUE TITLE
Traceback `ValidationError` on `on_evc_deployed` when validating uni tag_type value

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#306]
It turns out that `on_evc_deployed` this error happened `pydantic.main.BaseModel.__init__, pydantic.error_wrappers.ValidationError: 1 validation error for EVCBaseDoc, uni_a -> tag -> value,   value as string allows 'any' and 'untagged' (type=value_error)` on a e2e test execution. By default, `pydantic` is capable of converting an `IntEnum` like `TAGType.VLAN` as an int, but since we have a custom `@validator` we also need to handle that type accordingly. 

Here's the traceback for the record:

```
Apr  6 05:20:12 runner-rmtk68xb-project-107-concurrent-0 2023-04-06 05:20:12,086 (thread_pool_app_9) kytos.core.helpers:ERROR helpers:140:  listen_to handler: <function Main.on_evc_deployed at 0x7fd1cc6300d0>, args: (<Main(mef_eline, started 140538577483520)>, KytosEvent('kytos/mef_eline.deployed', {'evc_id': '9b97ab1ffc3b42', 'name': 'Vlan_100', 'metadata': {}, 'active': True, 'enabled': True, 'uni_a': {'interface_id': '00:00:00:00:00:00:00:01:1', 'tag': {'tag_type': <TAGType.VLAN: 1>, 'value': 100}}, 'uni_z': {'interface_id': '00:00:00:00:00:00:00:02:1', 'tag': {'tag_type': <TAGType.VLAN: 1>, 'value': 100}}}, 0)) traceback: Traceback (most recent call last):,   File "/usr/local/lib/python3.9/dist-packages/kytos/core/helpers.py", line 136, in handler_context,     result = handler(*args),   File "//var/lib/kytos/napps/kytos/mef_eline/main.py", line 807, in on_evc_deployed,     self.handle_evc_deployed(event),   File "//var/lib/kytos/napps/kytos/mef_eline/main.py", line 815, in handle_evc_deployed,     evc.setup_failover_path(),   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 795, in setup_failover_path,     self.sync(),   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 164, in sync,     self._mongo_controller.upsert_evc(self.as_dict()),   File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 324, in wrapped_f,     return self(f, *args, **kw),   File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 404, in __call__,     do = self.iter(retry_state=retry_state),   File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 349, in iter,     return fut.result(),   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result,     return self.__get_result(),   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result,     raise self._exception,   File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 407, in __call__,     result = fn(*args, **kwargs),   File "/usr/local/lib/python3.9/dist-packages/kytos/core/retry.py", line 25, in decorated,     return func(*args, **kwargs),   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/controllers/__init__.py", line 86, in upsert_evc,     model = EVCBaseDoc(,   File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__, pydantic.error_wrappers.ValidationError: 1 validation error for EVCBaseDoc, uni_a -> tag -> value,   value as string allows 'any' and 'untagged' (type=value_error), 
```

@Alopalao can you help to fix this?

**Comment by viniarck** [comment]
It might be worth including the `value` being validated [when raising `ValueError`](https://github.com/kytos-ng/mef_eline/blob/master/db/models.py#L50) to make it clearer when this happens.

**Comment by viniarck** [comment]
@Alopalao the enhanced error message turned out helpful, looks like the issue is coming from sending a invalid string `"bla"` during a `PATCH /v2/evc/<evc_id>` which we have mapped to be addressed on this issue https://github.com/kytos-ng/mef_eline/issues/291. I've assigned that issue to you, when you have a chance later on during this version `2023.1`. Until then, can you open a PR updating [this](https://github.com/kytos-ng/kytos-end-to-end-tests/blob/master/tests/test_e2e_13_mef_eline.py#L400) and [this](https://github.com/kytos-ng/kytos-end-to-end-tests/blob/master/tests/test_e2e_13_mef_eline.py#L218) test case to be skipped instead of xfail? Make sure to set the `reason` accordingly too in the decorator. Thanks

```
Apr 11 14:37:32 runner-rmtk68xb-project-107-concurrent-0 2023-04-11 14:37:32,259 (thread_pool_app_7) kytos.core.helpers:ERROR helpers:140:  listen_to handler: <function Main.on_evc_deployed at 0x7f7c4c06f040>, args: (<Main(mef_eline, started 140171156453120)>, KytosEvent('kytos/mef_eline.deployed', {'evc_id': 'bb927ede8f2b40', 'name': 'Vlan_100', 'metadata': {}, 'active': True, 'enabled': True, 'uni_a': {'interface_id': '00:00:00:00:00:00:00:01:1', 'tag': {'tag_type': <TAGType.VLAN: 1>, 'value': 100}}, 'uni_z': {'interface_id': '00:00:00:00:00:00:00:02:1', 'tag': {'tag_type': <TAGType.VLAN: 1>, 'value': 100}}}, 0)) traceback: Traceback (most recent call last):,   File "/usr/local/lib/python3.9/dist-packages/kytos/core/helpers.py", line 136, in handler_context,     result = handler(*args),   File "//var/lib/kytos/napps/kytos/mef_eline/main.py", line 807, in on_evc_deployed,     self.handle_evc_deployed(event),   File "//var/lib/kytos/napps/kytos/mef_eline/main.py", line 815, in handle_evc_deployed,     evc.setup_failover_path(),   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 795, in setup_failover_path,     self.sync(),   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 164, in sync,     self._mongo_controller.upsert_evc(self.as_dict()),   File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 324, in wrapped_f,     return self(f, *args, **kw),   File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 404, in __call__,     do = self.iter(retry_state=retry_state),   File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 349, in iter,     return fut.result(),   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result,     return self.__get_result(),   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result,     raise self._exception,   File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 407, in __call__,     result = fn(*args, **kwargs),   File "/usr/local/lib/python3.9/dist-packages/kytos/core/retry.py", line 25, in decorated,     return func(*args, **kwargs),   File "//var/lib/kytos/napps/../napps/kytos/mef_eline/controllers/__init__.py", line 86, in upsert_evc,     model = EVCBaseDoc(,   File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__, pydantic.error_wrappers.ValidationError: 1 validation error for EVCBaseDoc, uni_a -> tag -> value,   bla is not allowed as <class 'str'>. Allowed strings are 'any' and 'untagged'. (type=value_error), 
```

**Comment by Alopalao** [comment]
Tested those tests alone, now they passing with the PR [#310](https://github.com/kytos-ng/mef_eline/pull/310)
