### ISSUE TITLE
bug: mef_eline can crash if pathfinder returns HTTP 400 when discovering a new path

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/mef_eline#417]
[EVCDeploy.discover_new_paths()](https://github.com/kytos-ng/mef_eline/blob/master/models/evc.py#L501-L503) calls [DynamicPathManager.get_best_paths()](https://github.com/kytos-ng/mef_eline/blob/master/models/path.py#L174), `get_best_paths` which is a generator, but [`DynamicPathManager.get_paths`](https://github.com/kytos-ng/mef_eline/blob/master/models/path.py#L137) isn't, and it might return `None`, which isn't iterable, which in turn would crash the iteration over `get_paths`, so this needs to be handled accordingly either with a try except `TypeError` or conditional. 

How to reproduce:

- Load any topology with a link `metadata` with a wrong type, let's say `{"ownership": 1}`, it expects a string on links, so if `mef_eline` were to try to create an EVC with `"ownership"` mandatory constraints, then `pathfinder` will return HTTP 400: 

```
{
    "name": "epl",
    "service_level": 6,
    "dynamic_backup_path": true,
    "uni_a": {
        "interface_id": "00:00:00:00:00:00:00:01:1"
    },
    "uni_z": {
        "interface_id": "00:00:00:00:00:00:00:03:1"
    },
    "primary_constraints": {
        "mandatory_metrics": {
            "ownership": "blue"
        }
    },
    "secondary_constraints": {
        "mandatory_metrics": {
            "ownership": "blue"
        }
    }
}
```

```
2023-12-12 15:23:10,036 - ERROR [kytos.napps.kytos/mef_eline] [path.py:151:get_paths] (AnyIO worker thread) Failed to get paths at http://localhost:8181/api/kytos/pathfinder/v3/. Returned {"description":"argument of type 'int' is not iterable","code":400}
```

```
2023-12-12 15:23:10,035 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:55376 - "POST /api/kytos/pathfinder/v3/ HTTP/1.1" 400
2023-12-12 15:23:10,036 - ERROR [kytos.napps.kytos/mef_eline] [path.py:151:get_paths] (AnyIO worker thread) Failed to get paths at http://localhost:8181/api/kytos/pathfinder/v3/. Return
ed {"description":"argument of type 'int' is not iterable","code":400}
2023-12-12 15:23:10,037 - INFO [uvicorn.access] [httptools_impl.py:506:send] (MainThread) 127.0.0.1:55350 - "POST /api/kytos/mef_eline/v2/evc/ HTTP/1.1" 500
2023-12-12 15:23:10,037 - ERROR [uvicorn.error] [httptools_impl.py:441:run_asgi] (MainThread) Exception in ASGI application
Traceback (most recent call last):
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/applications.py", line 120, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/routing.py", line 716, in __call__
    await route.handle(scope, receive, send)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/routing.py", line 68, in app
    response = await run_in_threadpool(func, request)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/viniarck/repos/kytos/.direnv/python-3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/viniarck/repos/kytos/kytos/core/helpers.py", line 463, in wrapper_validate
    return func(*args, **kwargs)
  File "/home/viniarck/repos/napps/napps/kytos/mef_eline/main.py", line 312, in create_circuit
    evc.deploy()
  File "/home/viniarck/repos/napps/napps/kytos/mef_eline/models/evc.py", line 624, in deploy
    success = self.deploy_to_backup_path()
  File "/home/viniarck/repos/napps/napps/kytos/mef_eline/models/evc.py", line 594, in deploy_to_backup_path
    return self.deploy_to_path()
  File "/home/viniarck/repos/napps/napps/kytos/mef_eline/models/evc.py", line 840, in deploy_to_path
    for use_path in self.discover_new_paths():
  File "/home/viniarck/repos/napps/napps/kytos/mef_eline/models/path.py", line 176, in get_best_paths
    for path in cls.get_paths(circuit, **kwargs):
TypeError: 'NoneType' object is not iterable
kytos $>                                                                                                                                                                                 

```

@Ktmi since you're improving that part integrating with `pathfinder`, this is a low hanging fruit, if you could cover this and add a unit test that should be sufficient. `priority_low` though, but keep in your radar.

**Comment by viniarck** [comment]
I went ahead and fixed it myself, I already had the scenario ready to go, and it was a quick fix.
