### ISSUE TITLE
feature: EVCs need to be deleted after switch deletion

### ISSUE THREAD

**Issue by Alopalao** [kytos-ng/mef_eline#419]
After a switch is deleted, there are leftover EVCs that will prompt the next error if not removed:
```
kytos $> 2023-12-12 17:39:38,926 - ERROR [kytos.core.napps.base] (mef_eline) NApp: <Main(mef_eline, started 139921058666176)> unhandled exception Traceback (most recent call last):
  File "/home/aldo/Desktop/up/kytos/kytos/core/napps/base.py", line 257, in run
    self.execute()
  File "/home/aldo/Desktop/up/back/var/lib/kytos/napps/kytos/mef_eline/main.py", line 92, in execute
    self.execute_consistency()
  File "/home/aldo/Desktop/up/back/var/lib/kytos/napps/kytos/mef_eline/main.py", line 118, in execute_consistency
    if self.should_be_checked(circuit):
  File "/home/aldo/Desktop/up/back/var/lib/kytos/napps/kytos/mef_eline/main.py", line 104, in should_be_checked
    and circuit.are_unis_active(self.controller.switches)
  File "/home/aldo/Desktop/up/back/var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 1658, in are_unis_active
    interface_a = self.get_interface_from_switch(self.uni_a, switches)
  File "/home/aldo/Desktop/up/back/var/lib/kytos/napps/../napps/kytos/mef_eline/models/evc.py", line 1652, in get_interface_from_switch
    switch = switches[uni.interface.switch.dpid]
KeyError: '00:00:00:00:00:00:00:01'
```

Issue related from topology [#164](https://github.com/kytos-ng/topology/issues/164)

**Comment by Alopalao** [comment]
A decision has been made for all EVC related to a switch to be deleted by the user instead.
